M48
; DRILL file {KiCad 9.0.4} date 2025-11-02T13:51:21+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-02T13:51:21+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X2.2697Y-1.6339
X2.4606Y-1.6339
T2
X2.2579Y-1.5146
X2.4724Y-1.5146
M30
